---
title: Help a Jew. Help the Holy Land
timezone: UTC
collections:
  guides:
    title: Guides
    output: true
    layout: post
  posts:
    title: Posts
    output: true
    layout: post
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: guides
  values:
    layout: post
description: Help a Jew. Help the Holy Land</em> is a group of dedicated legal professionals
  who want to help those who have been denied their right to return to the Holy Land
url: http://haj.siteleaf.net/
email: name@domain.com
instagram: "//instagram.com"
twitter: "//twitter.com"
facebook: "//facebook.com"
phone: "+972 54 555 55 55"
address: 25 Mashukaze Street<br/>Tel Aviv-Yafo, 1231234<br/>Israel
permalink: "/:title"
image-placeholder: assets/img/placeholder.png
image-placeholder-2: assets/img/placeholder-2.png
image-placeholder-3: assets/img/placeholder-3.png
excerpt_separator: "<!--more-->"
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- ".idea"
