---
title: Help a Jew – Help the Holy Land
timezone: America/Chicago
collections:
  guide:
    title: Guides
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    thumbnail_image: ''
    author: ''
- scope:
    path: ''
    type: guide
  values:
    layout: guide
    thumbnail_image: ''
description: Help a Jew – Help the Holy Land is a charitable organization to help
  those who have been denied their right to return to the Holy Land. Help A Jew is
  a nonprofit corporation with IRS 501(c)(3) status.
baseurl: 
url: "//helpajew.com"
email: office@helpajew.com
linkedin: "//linkedin.com"
twitter: "//twitter.com"
facebook: "//facebook.com"
phone: "+44 7412 048124​⁠​"
address: 10200 US Hwy 290 W №301<br/> Austin, Texas 78736<br/>USA
permalink: pretty
image-placeholder: assets/img/image-placeholder.png
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- ".idea"
- ".sass-cache"
